Spring:
  application:
    name: movie-ticket-booking-system-api
  datasource:
    url: jdbc:mysql://localhost:3306/movie-ticket-booking-system?createDatabaseIfNotExist=true
    username: root
    password: Varsha1902:)
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
